//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChords.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenChords.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  D      D7        G         D
        ///Amazing grace how sweet the sound
        ///     Bm      E           A  A7
        ///that saved a wretch like me;
        ///  D        D7       G       D
        ///I once was lost but now I&apos;m found,
        ///    Bm        A     G   D
        ///was blind but now I see.
        ///
        ///     D          D7        G        D
        ///Twas grace that taught my heart to fear,
        ///    Bm       E       A      A7
        ///and grace my fears relieved;
        ///    D        D7       G       D
        ///How precious did that grace appear
        ///    Bm     A       G      D
        ///the hour I first belie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import1Input {
            get {
                return ResourceManager.GetString("Import1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [V1]
        ///. D      D7        G         D
        /// Amazing grace how sweet the sound
        ///.     Bm      E           A  A7
        /// that saved a wretch like me;
        ///.  D        D7       G       D
        /// I once was lost but now I&apos;m found,
        ///.    Bm        A     G   D
        /// was blind but now I see.
        ///
        ///[V2]
        ///.     D          D7        G        D
        /// Twas grace that taught my heart to fear,
        ///.    Bm       E       A      A7
        /// and grace my fears relieved;
        ///.    D        D7       G       D
        /// How precious did that grace appear
        ///.    Bm     A       G     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import1Output {
            get {
                return ResourceManager.GetString("Import1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  D      D7        G         D
        ///Amazing grace how sweet the sound
        ///     Bm      E           A  A7
        ///that saved a wretch like me;
        ///  D        D7       G       D
        ///I once was lost but now I&apos;m found,
        ///    Bm        A     G   D
        ///was blind but now I see.
        ///
        ///     D          D7        G        D
        ///Twas grace that taught my heart to fear,
        ///    Bm       E       A      A7
        ///and grace my fears relieved;
        ///    D        D7       G       D
        ///How precious did that grace appear
        ///    Bm     A       G      D
        ///the hour I first belie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import2Input {
            get {
                return ResourceManager.GetString("Import2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [V1]
        ///. D      D7        G         D
        /// Amazing grace how sweet the sound
        ///.     Bm      E           A  A7
        /// that saved a wretch like me;
        ///.  D        D7       G       D
        /// I once was lost but now I&apos;m found,
        ///.    Bm        A     G   D
        /// was blind but now I see.
        ///
        ///[V2]
        ///.     D          D7        G        D
        /// Twas grace that taught my heart to fear,
        ///.    Bm       E       A      A7
        /// and grace my fears relieved;
        ///.    D        D7       G       D
        /// How precious did that grace appear
        ///.    Bm     A       G     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import2Output {
            get {
                return ResourceManager.GetString("Import2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Verse 1]
        /// D      D7        G         D
        ///Amazing grace how sweet the sound
        ///     Bm      E           A  A7
        ///that saved a wretch like me;
        ///
        ///[CHORUS]
        /// My chains are gone
        ///
        ///[Verse 2]
        ///     D          D7        G        D
        ///Twas grace that taught my heart to fear,
        ///    Bm       E       A      A7
        ///and grace my fears relieved;
        ///    D        D7       G       D
        ///How precious did that grace appear
        ///    Bm     A       G      D
        ///the hour I first believed!
        ///
        ///[CHORUS]
        /// My chains are gone
        ///
        ///[Verse 3]
        ///        D     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import3Input {
            get {
                return ResourceManager.GetString("Import3Input", resourceCulture);
            }
        }
    }
}
