
// This file has been generated by the GUI designer. Do not modify.
namespace OpenChordsGtk
{
	public partial class EditorForm
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action Action;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.Table table1;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TreeView treeview2;
		private global::Gtk.Label label5;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Image image15;
		private global::Gtk.Image image4;
		private global::Gtk.Image image5;
		private global::Gtk.Image image14;
		private global::Gtk.VBox vbox3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry entry1;
		private global::Gtk.Image image1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Table table2;
		private global::Gtk.Entry entry3;
		private global::Gtk.Entry entry4;
		private global::Gtk.Entry entry5;
		private global::Gtk.Entry entry6;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label6;
		private global::Gtk.Entry txtKey;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Image image7;
		private global::Gtk.Image image8;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label7;
		private global::Gtk.Entry txtCapo;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Image image9;
		private global::Gtk.Image image10;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Image image11;
		private global::Gtk.Image image12;
		private global::Gtk.Image image13;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Label label8;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtLyrics;
		private global::Gtk.VBox vbox10;
		private global::Gtk.Label label9;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtNotes;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenChordsGtk.EditorForm
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "OpenChordsGtk.EditorForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("OpenChords");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.OpenChordsSourceForgeImage.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child OpenChordsGtk.EditorForm.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'/><menu n" +
				"ame=\'Action\' action=\'Action\'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 243;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 148;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.table1.Add (this.combobox1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox1]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow3.Add (this.treeview2);
			this.table1.Add (this.GtkScrolledWindow3);
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("[*]");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image15 = new global::Gtk.Image ();
			this.image15.Name = "image15";
			this.image15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Up.png");
			this.vbox4.Add (this.image15);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.image15]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Delete.png");
			this.vbox4.Add (this.image4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.image4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Present.png");
			this.vbox4.Add (this.image5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.image5]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image14 = new global::Gtk.Image ();
			this.image14.Name = "image14";
			this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Down.png");
			this.vbox4.Add (this.image14);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.image14]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			this.table1.Add (this.vbox4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox4]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vpaned1.Add (this.table1);
			global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.table1]));
			w12.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow2.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow2.Add (this.treeview1);
			this.vbox3.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow2]));
			w14.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w15.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Search.png");
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vpaned1.Add (this.vbox3);
			this.hpaned1.Add (this.vpaned1);
			global::Gtk.Paned.PanedChild w19 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned1]));
			w19.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(3));
			// Container child hbox2.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.WidthRequest = 530;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.table2.Add (this.entry3);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry3]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.table2.Add (this.entry4);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry4]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entry5 = new global::Gtk.Entry ();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '●';
			this.table2.Add (this.entry5);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry5]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entry6 = new global::Gtk.Entry ();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '●';
			this.table2.Add (this.entry6);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry6]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Author");
			this.label2.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Order");
			this.label3.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Reference");
			this.label4.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w27.TopAttach = ((uint)(3));
			w27.BottomAttach = ((uint)(4));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.table2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.table2]));
			w28.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 29;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Key");
			this.label6.Justify = ((global::Gtk.Justification)(1));
			this.hbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtKey = new global::Gtk.Entry ();
			this.txtKey.WidthRequest = 37;
			this.txtKey.HeightRequest = 37;
			this.txtKey.CanFocus = true;
			this.txtKey.Name = "txtKey";
			this.txtKey.IsEditable = true;
			this.txtKey.InvisibleChar = '●';
			this.hbox3.Add (this.txtKey);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtKey]));
			w30.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Up.png");
			this.vbox6.Add (this.image7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image7]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Down.png");
			this.vbox6.Add (this.image8);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image8]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.hbox3.Add (this.vbox6);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox6]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Capo");
			this.label7.Justify = ((global::Gtk.Justification)(1));
			this.hbox4.Add (this.label7);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtCapo = new global::Gtk.Entry ();
			this.txtCapo.WidthRequest = 37;
			this.txtCapo.HeightRequest = 37;
			this.txtCapo.CanFocus = true;
			this.txtCapo.Name = "txtCapo";
			this.txtCapo.IsEditable = false;
			this.txtCapo.InvisibleChar = '●';
			this.hbox4.Add (this.txtCapo);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txtCapo]));
			w36.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Up.png");
			this.vbox7.Add (this.image9);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.image9]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Down.png");
			this.vbox7.Add (this.image10);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.image10]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			this.hbox4.Add (this.vbox7);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox7]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox4]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w41.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Play.png");
			this.vbox8.Add (this.image11);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.image11]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.Repair.png");
			this.vbox8.Add (this.image12);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.image12]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.image13 = new global::Gtk.Image ();
			this.image13.Name = "image13";
			this.image13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenChords.PresentSong.png");
			this.vbox8.Add (this.image13);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.image13]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.hbox2.Add (this.vbox8);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox8]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 509;
			this.hpaned2.BorderWidth = ((uint)(3));
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.WidthRequest = 29;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Lyrics / Chords");
			this.label8.Justify = ((global::Gtk.Justification)(1));
			this.vbox9.Add (this.label8);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label8]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtLyrics = new global::Gtk.TextView ();
			this.txtLyrics.CanFocus = true;
			this.txtLyrics.Name = "txtLyrics";
			this.GtkScrolledWindow1.Add (this.txtLyrics);
			this.vbox9.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow1]));
			w49.Position = 1;
			this.hpaned2.Add (this.vbox9);
			global::Gtk.Paned.PanedChild w50 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.vbox9]));
			w50.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.WidthRequest = 29;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes");
			this.label9.Justify = ((global::Gtk.Justification)(1));
			this.vbox10.Add (this.label9);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label9]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtNotes = new global::Gtk.TextView ();
			this.txtNotes.CanFocus = true;
			this.txtNotes.Name = "txtNotes";
			this.GtkScrolledWindow.Add (this.txtNotes);
			this.vbox10.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.GtkScrolledWindow]));
			w53.Position = 1;
			this.hpaned2.Add (this.vbox10);
			this.vbox2.Add (this.hpaned2);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpaned2]));
			w55.Position = 1;
			this.hpaned1.Add (this.vbox2);
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w57.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1011;
			this.DefaultHeight = 700;
			this.Show ();
		}
	}
}
