//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenChords.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        {InlineStyleSheet}
        ///    &lt;/style&gt;
        ///    &lt;title&gt;HtmlPanel&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    {SongBody}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string BaseSongHtml {
            get {
                return ResourceManager.GetString("BaseSongHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* http://meyerweb.com/eric/tools/css/reset/ 
        ///   v2.0 | 20110126
        ///   License: none (public domain)
        ///*/
        ///
        ///html, body, div, span, applet, object, iframe,
        ///h1, h2, h3, h4, h5, h6, p, blockquote, pre,
        ///a, abbr, acronym, address, big, cite, code,
        ///del, dfn, em, img, ins, kbd, q, s, samp,
        ///small, strike, strong, sub, sup, tt, var,
        ///b, u, i, center,
        ///dl, dt, dd, ol, ul, li,
        ///fieldset, form, label, legend,
        ///table, caption, tbody, tfoot, thead, tr, th, td,
        ///article, aside, canvas, details, embed, 
        ///figure, figcapt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stylesheet {
            get {
                return ResourceManager.GetString("stylesheet", resourceCulture);
            }
        }
    }
}
